# CodeRabbit Configuration File

language: en-US
reviews:
  poem: false
  suggested_reviewers: false
  suggested_labels: false
  sequence_diagrams: false
  high_level_summary: true
  high_level_summary_placeholder: "@coderabbitai summary"
  profile: chill
  auto_review:
    enabled: true
    auto_incremental_review: true
  review_status: true
  commit_status: true
  changed_files_summary: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
chat:
  auto_reply: false

knowledge_base:
  # Don't opt out - this enables all learning features
  opt_out: false
  # Enable web search for up-to-date information
  web_search:
    enabled: true
  # Code Guidelines - automatically detects team standards
  code_guidelines:
    enabled: true
    filePatterns:
      # Add custom patterns here if you have other guideline files:
      - "apps/generator/docs/*"
      - "Development.md"
      - "CONTRIBUTING.md"
      - "apps/react-sdk/API.md"
  learnings:
    scope: auto
  issues:
    scope: auto
  pull_requests:
    scope: auto
  mcp:
    usage: auto
