name: Pull request testing

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  test_pr:
    if: github.event.pull_request.draft == false
    name: 'Testing pull request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install dependencies
        run: npm ci
      - name: Build project to make sure code is not broken
        run: npm run build
      - name: Run linter
        run: npm run lint
      - name: Run tests
        run: npm test
      - name: Regenerate docs to make sure jsdoc, markdown-toc etc. are not broken
        run: npm run docs