// This file is auto-generated by script triggered by "npm run build".
// DO NOT EDIT MANUALLY!

module.exports = [
  {
    "name": "@asyncapi/core-template-clients-websocket-dart",
    "path": "node_modules/@asyncapi/core-template-clients-websocket-dart",
    "type": "clients",
    "protocol": "websocket",
    "target": "dart"
  },
  {
    "name": "@asyncapi/core-template-clients-websocket-javascript",
    "path": "node_modules/@asyncapi/core-template-clients-websocket-javascript",
    "type": "clients",
    "protocol": "websocket",
    "target": "javascript"
  },
  {
    "name": "@asyncapi/core-template-clients-websocket-python",
    "path": "node_modules/@asyncapi/core-template-clients-websocket-python",
    "type": "clients",
    "protocol": "websocket",
    "target": "python"
  }
];
