{% set server = asyncapi.server(params.server) -%}
  {% if server.protocol() === 'amqp' -%}
amqp:
  # {{server.description()}}
  broker:
    host: localhost
    port: 5672
    username: guest
    password: guest
  exchange:
{%- for channelName, channel in asyncapi | publishChannels %}
    {{channel.publish().id()}}: {{channelName}}
{%- endfor %}
  queue:
{%- for channelName, channel in asyncapi | subscribeChannels %}
    {{channel.subscribe().id()}}: {{channelName}}
{%- endfor %}
  {%- endif -%}
  {% if server.protocol() === 'mqtt' -%}
mqtt:
  # {{server.description()}}
  broker:
    scheme: tcp
    host: {{server.url()}}
    port: {{server.variable('port').defaultValue()}}
    username:
    password:
  channel:
{%- for channelName, channel in asyncapi.channels() %}
    {{channel.publish().id() if channel.hasPublish() else channel.subscribe().id()}}Channel: {{channelName}}
{%- endfor %}
  {% endif %}