name: PR Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
  
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerging if all conditions are met
        uses: ridedott/merge-me-action@v1.1.8
        with:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_LOGIN: derberg