name: PR Automerge

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  status: {}
  
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: Automerging if all conditions are met
        uses: "pascalgn/automerge-action@v0.7.5"
        with:
          args: "--trace"
        env:
          GITHUB_TOKEN: "${{ secrets.GH_TOKEN }}"
          MERGE_LABELS: "automerge"
          MERGE_REMOVE_LABELS: "automerge"
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "pull-request-title"
          MERGE_FORKS: "true"
          MERGE_RETRIES: "10"
          MERGE_RETRY_SLEEP: "10000"