name: PR Review Checklist

on:
  pull_request_target:
    types: 
      - opened

jobs:
  pr-review-list:
    name: Post PR Review Checklist
    # it runs only if PR actor is not a bot, at least not a bot that we know
    if: |
      (github.event.pull_request.user.login != 'asyncapi-bot' && 
      github.event.pull_request.user.login != 'dependabot[bot]' && 
      github.event.pull_request.user.login != 'dependabot-preview[bot]') 
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Post initial PR checklist
      uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5.0.0
      with:
        token: ${{ secrets.GH_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body-path: '.github/pr-review-checklist.md'