name: Verifying PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
    - name: semantic-pull-request
      uses: amannn/action-semantic-pull-request@v1.2.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}