name: Verifying PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
    - name: Checking PR title 
      uses: aslafy-z/conventional-pr-title-action@v2.2.0
      with:
        success-state: 'Pull request title follows the Conventional Commits specification.'
        failure-state: 'Pull request title does not follow the the Conventional Commits specification. Consult the contribution guide.'
        context-name: Checking PR title 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}