name: Validating PR

on:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize
    branches:
      - master

jobs:
  pr-title-check:
    runs-on: ubuntu-latest
    steps:
    - name: 'Check for PR title with conventional commits'
      uses: amannn/action-semantic-pull-request@v1.1.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}