name: Checking if list of templates is up to date

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  templates:
    name: 'Check list of templates'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - uses: ./.github/templates-list-validator
        with:
          token: ${{ secrets.GITHUB_TOKEN }} 