name: Update latest generator documents in the website

on:
  push:
    branches:
      - 'master'
    paths:
      - 'docs/*.md'

jobs:
  Make-PR:
    name: Make PR on website repository with updated latest generator docs
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@v2
        with:
          path: generator
      - name: Checkout Another repository
        uses: actions/checkout@v2
        with:
          repository: asyncapi/website
          path: website
          token: ${{ env.GITHUB_TOKEN }}
      - name: Config git
        run: |
          git config --global user.name asyncapi-bot
          git config --global user.email info@asyncapi.io
      - name: Create branch
        working-directory: ./website
        run: |
          git checkout -b update-generator-docs-${{ github.sha }}
      - name: Copy generator folder from Current Repo to Another
        working-directory: ./website
        run: |
          mkdir -p ./pages/docs/tools/generator
          cp -R ../generator/docs ./pages/docs/tools/generator
          printf "\`\`\`\ntitle: Generator\nweight: 3\n\`\`\`" > _section.md
      - name: Commit and push
        working-directory: ./website
        run: |
          git add .
          git commit -m "docs(generator): update latest generator docs"
          git push https://${{ env.GITHUB_TOKEN }}@github.com/asyncapi/website
      - name: Create PR
        working-directory: ./website
        run: |
          gh pr create --title "docs(generator): update latest generator documentaion" --body "Updated generator docs are available and this PR introduces update to generator folder on the website" --head "update-generator-docs-${{ github.sha }}"