name: Update generated parts of documentation on docs: commits

on:
  - pull_request

jobs:
  docs-gen:
    name: 'Generate docs and create PR'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13
      - name: Install dependencies
        run: npm ci
      - name: Regenerate docs
        run: npm run docs
      - name: Generate README ToC
        run: npm run gen-readme-toc
      - name: console.log event 
        run: echo ${{ github.payload }}
     # - name: Create Pull Request with updated docs
      #  uses: peter-evans/create-pull-request@v2.4.4
       # with:
        #  token: ${{ secrets.GH_TOKEN }}
         # commit-message: 'chore: update generated docs'
    #      committer: asyncapi-bot <info@asyncapi.io>
     #     author: asyncapi-bot <info@asyncapi.io>
      #    title: 'chore: update generated docs'
       #   body: 'Update of docs that are generated and were forgotten on PR level.'
        #  branch: gen-docs-update
