name: Update latest generator documentation in the website

on:
  push:
    branches:
      - 'master'
    paths:
      - 'apps/generator/docs/*.md'
      - '.github/workflows/update-docs-in-website.yml'

permissions: {}

jobs:
  Make-PR:
    name: Make PR on website repository with updated latest generator documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write       # push to asyncapi/website via PAT
      pull-requests: write  # gh pr create
    env:
      GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
      - name: Checkout Current repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: generator
          persist-credentials: false # since this repo only used for reading docs
      - name: Checkout The Website repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          repository: asyncapi/website
          path: website
          token: ${{ env.GITHUB_TOKEN }}
          persist-credentials: true  # needed for git push of the docs to the website repo

      - name: Config git
        working-directory: ./website
        run: |
          git config --global user.name asyncapi-bot
          git config --global user.email info@asyncapi.io

      - name: Create branch
        working-directory: ./website
        env:
          SHA: ${{ github.sha }}
        run: |
          git checkout -b "update-generator-docs-${SHA}"

      - name: Copy generator folder to the website repo
        working-directory: ./website
        run: |
          rm -r ./markdown/docs/tools/generator
          mkdir -p ./markdown/docs/tools/generator
          rm ../generator/apps/generator/docs/README.md
          rm -r ../generator/apps/generator/docs/jsdoc2md-handlebars
          printf "%s\ntitle: Generator\nweight: 3\n%s" "---" "---"> ../generator/apps/generator/docs/_section.md
          mv ../generator/apps/generator/docs/*.md ./markdown/docs/tools/generator

      - name: Commit and push
        working-directory: ./website
        run: |
          git add .
          git commit -m "docs(generator): update latest generator docs"
          git push origin HEAD
          
      - name: Create PR
        working-directory: ./website
        run: |
          gh pr create --title "docs(generator): update latest generator documentation" --body "Updated generator documentation is available and this PR introduces update to generator folder on the website" --head "update-generator-docs-${{ github.sha }}"
