name: Welcome first time contributors

on:
  pull_request_target:
    types: 
      - opened
  issues:
    types:
      - opened

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: |
          Welcome to AsyncAPI. Thanks a lot for reporting your first issue.

          Keep in mind there are also other channels you can use to interact with AsyncAPI community. For more details check out [this issue](https://github.com/asyncapi/asyncapi/issues/115).
        pr-message: |
          Welcome to AsyncAPI. Thanks a lot for creating your first pull request.

          Keep in mind there are also other channels you can use to interact with AsyncAPI community. For more details check out [this issue](https://github.com/asyncapi/asyncapi/issues/115).
